### ISSUE TITLE
Widget: Pressable Component

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/mix#1]
There is a need to create components that can be interacted with but easily styled. Right now this is not a problem as you can style all the components and wrap them in an InkWell or a GestureDetector, however, the creation of a `Pressable` component opens up some other possibilities.
- Ability to provide styling for interactions, `tap`, `hover`, `disabled` etc.
- Clean syntax for creating buttons and other pressable components using Mix

**Comment by bdlukaa** [comment]
This should be something like:

```dart
PressableMix(
  Mix(
    disabled(* DISABLED MIX HERE *),
    pressing(* PRESSING MIX HERE *),
    hovering(* HOVERING MIX HERE *),
  )
)
```

**Comment by leoafarias** [comment]
@bdlukaa that is a great suggestion for the API. Right now the Mix Widgets are stateless, but I am thinking this one will have to be stateful in order to implement those states.

**Comment by bdlukaa** [comment]
Indeed. I already have something, I can make a PR

**Comment by leoafarias** [comment]
#3 merged
