### ISSUE TITLE
MixWidget

### ISSUE THREAD

**Issue by bdlukaa** [leoafarias/mix#21]
*Feature request*

`MixWidget` would be an extendable `Widget` that would provide the combination of `defaultMix` and `mix` to the `build` method

```dart
class CheckboxX extends MixWidget {
  const CheckboxX({
    Key? key,
    required this.checked,
    required this.onChanged,
    Mix? mix, 
  }) : super(mix: mix, child: null);
  
  final bool checked;
  final VoidCallback onChanged;

  @override
  Mix get defaultMix => ...;
  
  @override
  Widget build(BuildContext context, Mix mix) {
    return ...;
  }
}
```

I would love to hear your thoughts on this

**Comment by leoafarias** [comment]
@bdlukaa I have been thinking about doing a `RemixWidget` that allows setting a default, but be overridden. I think that would solve that problem. The `Mix` widget does not have a default and it's used for the Box and so on.

I think a Remix widget could allow better API for variants.

**Comment by leoafarias** [comment]
Added a widget called `RemixableWidget` probably will elaborate on this further. Also renamed `MixWidget` to `MixableWidget`
