### ISSUE TITLE
Use in decorating existing widgets?

### ISSUE THREAD

**Issue by oravecz** [leoafarias/mix#30]
Can (or will) I be able to style something like a `TextField` using Mix? Can I access design tokens outside of a `BuildContext`, or within the `BuildContext` of a standard widget?

**Comment by leoafarias** [comment]
To allow for mixing a `TextField` we might have to create it as a headless widget, to keep it outside of basic primitives. Design tokens can be accessed outside of `BuildContext`. 

I will close this ticket and keep track of the TextField on #46
