### ISSUE TITLE
Documentation: Organize dartdoc API output

### ISSUE THREAD

**Issue by rickbsgu** [leoafarias/mix#33]
dartdoc lumps all of the classes together without any distinction.  Same with functions, constants, etc.

These need to organized under header by type, category, etc.

Not straightforward.  Investigating.

**Comment by rickbsgu** [comment]
I'm making some progress using the 'categories' feature in dartdoc.

By tagging classes with the following (in the prefixing comment):
```
/// {@category Some Category}
```
and making some entries in dartdoc_options.yaml along with some commandline options, dartdoc lists the categories in the left sidebar under 'topics'.  Clicking on a category lists the classes tagged with that category.

**Comment by rickbsgu** [comment]
Here's what I've been able to do, so far.  Note the categories may not be correct or complete - this just shows how it works.

https://rickbsgu.github.io/mix/apidoc/

Note the 'Topics' column in the left side bar.  You can click on any of those for a list of classes that fall under that 'Topic' (category).

**Comment by leoafarias** [comment]
@rickbsgu this looks really good! This will make things much easier to navigate.

**Comment by rickbsgu** [comment]
Version 2: Instead of 'categories', I've listed the source in multiple libraries.

Location: my fork https://github.com/rickbsgu/mix, branch rickb-docs-2.
Docs output webpage: https://rickbsgu.github.io/mix/apidoc/

------

The overall 'mix' library is still there, it's just excluded from the documentation generation so that it doesn't generate duplicate content.  The 'mix' library exports the category libraries rather than the lower level source files.

I ran the tests to make sure this works - it all seems to work just fine.

I think this may be a better way to go rather than by categories by virtue of the fact that everything that is in that library gets documented as part of that library - global functions, constants, extensions, etc.  Categories only includes classes (as far as I've been able to tell.)

Note that we can exclude content as we want.

Downsides:
- I think we may have to do a bit of source reorganizing to get the libs to reflect categories properly.
- We have to name the separate libraries according to the dart convention - e.g. I'd rather it listed "mixable_widgets" as "Mixable Widgets", but we don't have control over that.
- Don't have control over the ordering of the libraries.  I'd like to list the more important ones first.  One way to do that would be to prefix the library name.

I don't think any of these are show-stoppers.

**Comment by rickbsgu** [comment]
I lifted the 'variants.dart' file to the 'lib' level so it documents and exported it in the 'mix' library.

**Comment by rickbsgu** [comment]
Been using the 'Variants' page to work out this organization, filling in a lot of details.

Think it's working really well.  See the results at the docs output webpage (prior comment).

Going to break out the 'Decorators' into their own topic, next.

**Comment by rickbsgu** [comment]
Ok, I've worked this out using pseudo-libraries to break up the dartdoc output into topics.  It is unorthodox and it's a bit ugly, because I have to create the psuedo-library topics using dartdoc's naming conventions to reflect a hierarchy.

To see the result look here: https://rickbsgu.github.io/mix/doc/api/ (different from above)
My fork: https://github.com/rickbsgu/mix, branch rickb-docs-3

However, I think it presents an organization that makes sense.  

#### Driving considerations for the organization are:
1. The first thing the user needs to know is "What is the Mix object?"
1. The next thing is "What can I use a Mix in?" (the Mixable Widgets section.)
1. The next thing is "What can I use to fill in a Mix?" (the Utilities section.)
1. The next thing is "What Attributes do the Utilities create, and what other kinds of Attributes and Utilities are there? (the Attributes section.)
1. Adding much else is noise and confusion.  If they need more detail, that's what the source is for.

The Attributes section is kind of tricky, because, ultimately, you don't really deal with attribute classes, directly: you instantiate them with the utilities and then forget them.  As such, documenting the individual attribute classes just adds more noise, with the constants and naming replication.  That can be referenced from the source, if need be. 

#### Driving considerations for the methodology are:
1. Documentation needs be autogenerated as much as possible &mdash; any updates in constants, functions, class names, etc.  need to be reflected automatically.
1. The dartdoc output needs to be organized and cleared of confusing noise.
1.  Items need to be linkable from other relevant items, but without presenting a bunch of noise in the process.  See the 'TextMix' item for an example &mdash; note the widget and directive utilities are referenced in the commenting, rather than just lumped in with the rest of the exports.

The only manual intervention necessary has been to list out the default values in the '.X' widgets, which I think are important to document.  Currently, I'm just copying the settings out of the default function.  Could eliminate this step if we could create a static class or map or some such thing that dartdoc will pick up and then return _that_ from the default Mix function.  I haven't figured out a way to do that, yet & my goal at this point has been to not disturb the source.

#### Summary
I think this provides a good API framework, and can be used to drive further documentation efforts (the guide.) Furthermore, the framework provides lots of logical places to drop in further commenting and references as we go.

In my mind, one ultimately needs a good API reference.  Everything else derives from that.

**Comment by rickbsgu** [comment]
Requested feedback:

1. [ ] Please comment on the approach.
2. [ ] Please comment on the organization.
3. [ ] Review topic by topic (ongoing.)
    - Correct wrong information/wording.
    - Fill in missing information.
    - Additional organization/links, etc.

**Comment by rickbsgu** [comment]
Well, after actually using it, I'm less convinced it's useful as it is.

Have to think on it some more.

**Comment by rickbsgu** [comment]
Ok, after a bit of a hiatus, I've taken another swing at this.  I think this effort works much better.

My fork and branch: https://github.com/rickbsgu/mix/tree/rickb-docs-4
Resulting docs: https://rickbsgu.github.io/mix/doc/api/

### Points:
- I've gone back to tagging the classes with categories (these turn up as _Topics_).  Each 'Topic' (category) page lists the classes tagged with that topic.
- I've added forward and backward links to ease navigation between widget and relevant attributes/utilities for that widget.
- The difficulty has been _Short Utils_.  Because they're global, they get dumped in the global space and don't fall under any topic &mdash; it's very confusing.  The approach taken here has been two-fold:
   - Put the _Short Utils_ classes in the _nodoc_ list in the _dartdoc_options.yaml_ file so they don't document.
   - In the respective _Utility_ class, under each static function that sets an attribute, add a canonical comment listing the short util for that function:

Example:
```
class BoxUtility {
  ...
  /// Short Utils: marginRight, mr
  static BoxAttributes marginRight(double value) {
    return BoxAttributes(margin: EdgeInsetsDto.only(right: value));
  }
  ...
  /// Short Utils: bgColor
  static BoxAttributes backgroundColor(Color color) =>
      BoxAttributes(color: color);
  ...
```
Now, in the documentation for the _BoxUtility_ class _Static Functions_ list, the output looks like this:

> [backgroundColor]()([Color]> >() color) → [BoxAttributes]()
> Short Utils: bgColor
>
> [marginRight]()([double]() value) → [BoxAttributes]()
> Short Utils: marginRight, mr

### Upsides
- By putting files in the _nodoc_ list, or adding _@nodoc_ tags in the code to remove code elements, the API docs are greatly reduced, noise is greatly reduced, and the user should be able to get to what they want to reference.  Forward and backward links between relevant classes helps the navigation for a given widget.
- Listing the _Short Utils_ with their respective static _Utility_ class functions ties them together.  This has added benefits, listed below.

### Downsides
- The approach is labor-intensive.  Category tags have to be added to each class/item you want categorized.  _nodoc_ listing has to be maintained in the _dartdoc_options.yaml_ file.  _Short Utils_ need to be listed by hand.

### Side Benefits
A side benefit of this approach has been that it exposes inconsistencies and omissions.

For about a day and a half, I was banging my head trying to figure out why the file _text_directives.utils.dart_ wasn't getting picked up by _dartdoc_.  (I even dug into _dartdoc_'s source code trying to figure out what was happening &mdash; pretty dense code...).

The issue turned that out it wasn't included the nested _exports.dart_ file.

Several _Short Codes_ are inconsistently defined, or missing.  For instance, for the _BoxUtility.marginHorizontal()_ function, the corresponding _Short Codes_ are _marginHorizontal, marginX,_ and _mx_, but for the _BoxUtility.paddingHorizontal()_ function we have _paddingHorizontal_ and _px_, but no _paddingX_.  Also, we have _BoxUtility_ and _TextUtility_ but _TextDirectiveUtils_.  Some of the static utility functions are defined as arrow functions and some are defined with normal braced function syntax (simple return functions.)

Admittedly these are minor points, but inconsistencies can be glaring to a user &mdash; when you're cooking along, it can be jarring to have to check to see if a utility class ends in _'...Utils'_ or _'...Utility_', or find out that an expected _Short Code_ like  _paddingX_ isn't there.

### Synopsis
It's not perfect &mdash; ideally the _Short Codes_ would be automatically generated in a way that collects them with their corresponding widget & we wouldn't have to do so much manually.

But, the approach has the benefit of keeping the _Short Codes_ with their _Utility_ functions and, the attention required to document them exposes inconsistencies and omissions.

It's a PITA, but I think it's worth it.

**Comment by leoafarias** [comment]
@rickbsgu This looks really good!! I believe there could be some adjustment to the category Mix Object, but I think overall the topics is the way to go!

**Comment by rickbsgu** [comment]
Ok.  I've refactored the decorator classes to be more in line with the rest of the classes, especially with regards to utilities and short utils and how they show up in the documentation.

This shouldn't introduce any breaking changes - all the class names are the same and the _Mix_ exports are the same.  I'll be checking this further.

Relevant changes:
- Created the files 'decorator_utils.dart' and 'decorator_short_utils.dart'
- Moved all of the global 'utility' functions in each of the decorator classes into corresponding _&lt;decorator&gt;Utility_ classes in 'decorator_utils.dart' as static member arrow functions.
-  Created short utils for all in the file 'decorator_short_utils.dart'.
- Renamed the 'clip_utilities/clip_rrect.dart' file to 'clip_decorator.dart'.
- Removed the 'clip_utilities/clip_utils.dart' file and moved the TriangleClip class into the 'clip_decorator.dart file.
- Converted the rest of the clip 'utility' globals to static ClipDecoratorUtility members the same as the other decorator utilities, along with short codes.

The result is the decorator class definitions are now consistent with the the rest of the attribute definitions, and document consistently.

**Comment by leoafarias** [comment]
That is great news!!!

**Comment by rickbsgu** [comment]
I think we can close this with the pull merge.
