### ISSUE TITLE
Gradient

### ISSUE THREAD

**Issue by Solido** [leoafarias/mix#44]
I'm investing in Mix and work on real designs so I'm trying to see how far I can implement a design lang. Thx!

A linear 2 colors with start/end position would already cover most of the cases.

Some very basics reflections:

TopLeft, BottomRight
`gradient(tl, br, Colors.white, Colors.blue, .0, .72);`

`vGradient(Colors.white, Colors.blue)` top to bottom .0 => 1

`hGradient(Colors.white, Colors.blue)` left to right .0 => 1

**Comment by Solido** [comment]
Ah thanks Leo, I am very very interested to see if I can green-light this library for more advanced projets. Having some examples would convince me even more quickly jajaja.

**Comment by leoafarias** [comment]
@Solido we are still in pre 1.0, but we will have some exciting news soon all around these tools to fill some of the gaps, especially material and documentation, and ongoing support.

**Comment by Solido** [comment]
This was my next question, should I point my pubspec to git or will there be a pub.dev pre-release? Will dig today and tomorrow on your works. Thanks to you and the whole team!

**Comment by leoafarias** [comment]
@Solido we will be updating pub soon, just have to automate some things on our end but should be done this week.
