### ISSUE TITLE
rounded() as r()

### ISSUE THREAD

**Issue by Solido** [leoafarias/mix#55]
Need a lot of caution before choosing a single letter but I would like to see `r(12)`.
Listening to your feedback about this. Robert

**Comment by leoafarias** [comment]
Yes, I was reserving the one letter for more spacing items, but this might make sense. I have seen the use of `radii`, just not sure about how much better it is ;)

**Comment by Solido** [comment]
r() should be applied to the most common use case ...
Not sure which one it is ;)

**Comment by leoafarias** [comment]
Yes I think it makes sense.. what about the cases of `rounded top left`, do you see the use of `rtl`, or would just apply for the overall rounded.

**Comment by Solido** [comment]
I would see `rtl`
Downside maybe the perception for new developer like `h` and `height` but once you get the mechanics you have an expressive one liner for often used design.
