### ISSUE TITLE
Pressable freezes on press when onPressed: null

### ISSUE THREAD

**Issue by VladimirCores** [leoafarias/mix#59]
Face a problem with Pressable - when click/press on the button with `onPressed: null` it freezes within press state. 

Mix (mix different colors):
```
  final mixButton = Mix(
    p(4),
    rounded(4),
    (hover)(
      bgColor(Colors.red.withOpacity(0.1))
    ),
    (press)(
      bgColor(Colors.red.lighten())
    ),
  );
```  

![image](https://user-images.githubusercontent.com/442111/158595767-4f93f82c-6a3e-4d2f-9d02-814da17006bd.png)

**Comment by bdlukaa** [comment]
When `onPressed` is `null`, `Pressable` assumes it is in its disabled state. To enable it, provide `onPressed`

**Comment by VladimirCores** [comment]
@bdlukaa alright, have you tried to `Pressable` widget which has `onPressed: null` and mix I posted in the description? It will freeze in `press` state.

**Comment by bdlukaa** [comment]
Yes! I am able to reproduce it
