### ISSUE TITLE
Feature: Better design tokens / theming

### ISSUE THREAD

**Issue by leoafarias** [leoafarias/mix#6]
In order to make the experience of designing easier and more customizable is important to allow the consumer of the design system to override values by using a config/theme.

Because Mix can be defined anywhere without a BuildContext, it means the attribute needs to reference where to look for within the Context definition or fall back to a default.

This is currently being done for some of the dynamic attributes like DarkMode. However, the implementation would look something like this for a `primaryColor`

```dart
get customMix = Mix(bgColor(primaryColor());
```

There could be an implementation leveraging material theming, in this case, we could leverage the material theme configuration.

```dart
get customMix = Mix(bgColor(mixTheme.primary);
```

However, the same configuration would need to apply for things like font sizes, or spacing like margin and padding. The ideal API would look for something like this. In order to implement the configured `large` spacing.

```dart
get paddingMix = Mix(p.l);
get marginMix = Mix(m.l);
```

In this example, the developer will know that they are getting a consistent sizing, but also it allows them to override through a configuration size.

```dart
const theme = MixTheme.copyWith(space: [0,4,8,16,32, 64]);
```

This would configure the sizing for `m.none`, `m.xs`, `m.s`, `m.m`, `m.l` and `m.xl`

The same could be applied to rounded borders.

```dart
const theme = MixTheme.copyWith(radii: [0,4,8,16,32, 64]);

final boxMix = Mix(rounded.l);
```

### Using String tokens as references.
A simpler implementation that could provide a lot of flexibility would be the definition of tokens.

```dart
final boxMix = Mix(token('bg'));
```

When the following above runs it would look for an attribute that has the index of `bg`. The biggest downside with this approach is that you would lose all typing, but would allow for a lot of flexibility going forward.

### Problems to solve
- How to allow the use of context values within a Mix with a clean and minimal API.
- Can we provide attribute methods, or extensions to allow for pulling those context values through `rounded.l` for example?
- How to implement Material theme configuration like color swatches to mixes without having to do `Theme.of(context).colorSwatches.primary`, instead of using more reference attributes or tokens like `materialTheme.primary`.

### Prior art
- https://system-ui.com/theme
- https://styled-system.com/api/

**Comment by bdlukaa** [comment]
We could provide a mixing for this

```dart
class Foo with MixThemeProvider {
  static boxMix = Mix(theme.primary);
}
```

And we could have a `MixTheme` inherithed widget that provides the theme for all the widgets below it.
