### ISSUE TITLE
Conditional rendering of inner component on Pressable hover 

### ISSUE THREAD

**Issue by VladimirCores** [leoafarias/mix#60]
Is there any way I can render elements inside `Pressable` on `hover`?
I need to render control buttons inside hovered row, like this:

![image](https://user-images.githubusercontent.com/442111/158657090-15779049-ac7c-4551-bb23-a0fc288ada79.png)

**Comment by leoafarias** [comment]
@VladimirCores there are a `hide()` and `show()` attribute that you can pass the conditional to it.

**Comment by VladimirCores** [comment]
Tried, it works, thank you @leoafarias, love the library : )

**Comment by leoafarias** [comment]
Thank you! @VladimirCores we are lacking a bit on the docs front but should catch up soon
